version: 2

# 构建环境配置
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Python 依赖安装
python:
  install:
    - path: .
      extra_requirements:
        - docs

# Sphinx 配置
sphinx:
  configuration: docs/conf.py