# .readthedocs.yaml

version: 2

# Build tools and environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Install dependencies using Poetry
python:
  install:
    - method: poetry
    - method: pip
      path: .
      extra_requirements:
        - docs

# Sphinx configuration
sphinx:
  configuration: docs/conf.py