version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - method: poetry

sphinx:
  configuration: docs/conf.py

build:
  commands:
    - pip install poetry
    - poetry install --extras docs